server:
  port: 8083
spring:
  application:
    name: business-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/vibecode_business
app:
  cors:
    allowed-origin: http://localhost:3000,http://localhost:3001
